---
    # default EE does not have timezone files hence using +8 hours
    - name: Create Time Stamp in SGT Timezone
      set_fact:
        datetime: "{{ lookup('pipe', datecmd) }}"
      delegate_to: localhost
      delegate_facts: true
      run_once: true
      vars:
        datecmd: "date -d '+8 hour' +%Y-%m-%d-%H-%M"

    - name: Backup Running-Config to SCP Server
      cisco.ios.ios_command:
        commands: 
          - command: 'copy running-config scp:'
            check_all: true
            prompt:
              - 'Address or name of remote host \[\]\?'
              - 'Destination username \[.*\]\?'
              - 'Destination filename \[.*\]\?'
              - 'Password\:'
            answer: 
              - "{{ scp_server }}"
              - "{{ scp_server_user }}"
              - "{{backup_base_folder_path}}{{ inventory_hostname }}/{{backup_file_prefix}}{{hostvars['localhost'].datetime}}.cfg"
              - "{{ scp_server_password }}"

    - name: Print backup file Name
      debug:
        msg: 
          - "backup file : {{backup_file_prefix}}{{hostvars['localhost'].datetime}}.cfg"
      run_once: true 