---
- name: Provision AI infrastructure
  hosts: localhost
  gather_facts: false
  vars:
    rhelai_aws_instance_type: g6.2xlarge  # AWS instance type out of g6 family
    rhelai_aws_rhelai_ami: 'ami-071f0b79c29feaa2a'  # AMI for RHEL AI on AWS
    rhelai_aws_resource_name: "vk_rhelai_1"  # Names your EC2 instance
    rhelai_aws_aws_region: us-east-2
    rhelai_aws_vpc_cidr: "10.0.0.0/16"
    rhelai_aws_subnet_cidr: "10.0.1.0/24"
    rhelai_aws_create_eip: true  # Set to true to create a new Elastic IP
    rhelai_aws_key_name: "vk-rhelai-ssh-key"
    rhelai_aws_key_material: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDArxrjPfUPJFHKeD+r6qW+KbJ2IXaErrEqmewm2JqoXlgelQkMIJ/8UsvGsaw3ovzN7nczhiixHGPRQ5YrfHU59Hu56QZUQmqmz4CasmpwoGq8MKG7bKlEnqv1vC7tWob9rkOYigljTOpGGHnWjzx8Jwy3aYJmLnEVAofiwlDRDcovYWqwGpCw+X+gT5J0N+2MzT3bFv7kEjTj0ToIOaOLoR60c9U+I1MT8m+7hHkeAC4bvkDAzUu9UjmyZwPzR6ECsztLWGnNTa4fEhKKSfBR/eeGfrNYasq2jh7ewjEjoZUDTZqnCL2kdkrKKBRSNsXLddjj8XmLu1WZdX6wlFjKmUYXcDQAiKbeVRZwz3Nl8E0g1MUYtXZxGJCDnGI2WmFXLtDdPsYrD4OmbcVEesDfF2kOKVNlOHp1v2cuKAsAKhFY0s491woz98Nzg8WS6hGQkOZ781KLEeoyCiPEUeXJS7Za3dro5LTwRhhsgSH5ntFCozGOxASSLvG309pkmZqMsXVNsowl5FdUB2Ub6Ykj4eMu+XqU3z/S4OQZJZDbW5aFApEYRC4+52caLfXupaJrU26v4qdDDHpkmJINM6nW5P5+jRGwAsKUh1nXK3+SGJ0Qc/ORSshee+iwP83bWRTWScjV07zD0vFaxk7i7kLbEm95ewUplm/I9otGKVrt1w==" 
  tasks:
    - name: Orchestrate
      vars:
        rhelai_aws_key_default_name: "{{ rhelai_aws_resource_name }}-key"
      module_defaults:
        group/aws:
          aws_access_key: "{{ aws_access_key | default(lookup('ansible.builtin.env', 'AWS_ACCESS_KEY')) }}"
          aws_secret_key: "{{ aws_secret_key | default(lookup('ansible.builtin.env', 'AWS_SECRET_KEY')) }}"
          #aws_security_token: "{{ security_token | default(lookup('ansible.builtin.env', 'SECURITY_TOKEN')) }}"
      environment:
        AWS_REGION: "{{ rhelai_aws_aws_region | default(lookup('ansible.builtin.env', 'AWS_REGION')) }}"

      block:
        - name: Setup credentials
          ansible.builtin.include_role:
            name: cloud.aws_ops.aws_setup_credentials

        # - name: Fetch keypair if key name is defined
        #   amazon.aws.ec2_key_info:
        #     names:
        #       - "{{ rhelai_aws_key_name }}"
        #   register: keypair_info
        #   when: rhelai_aws_key_name is defined and rhelai_aws_key_name | length > 0

        - name: Create AWS key pair
          # vars:
          #   key_name: >-
          #     {{
          #       rhelai_aws_key_name if rhelai_aws_key_name | default('') | length > 0 else
          #       rhelai_aws_key_default_name
          #     }}
          #   key_material: >-
          #     {{
          #       rhelai_aws_key_material if rhelai_aws_key_material is defined and
          #       rhelai_aws_key_material | default('') | length > 0
          #       else omit
          #     }}
          amazon.aws.ec2_key:
            name: "{{ rhelai_aws_key_name }}"
            region: "{{ rhelai_aws_aws_region }}"
            key_material: "{{ rhelai_aws_key_material }}"
            state: present
          register: aws_key
          when: rhelai_aws_key_name is defined and rhelai_aws_key_material is defined 
            # (
            #   rhelai_aws_key_name | length > 0 and
            #   rhelai_aws_key_material | default('') | length > 0 and
            #   (
            #     keypair_info is undefined or
            #     keypair_info.keypairs is undefined or
            #     keypair_info.keypairs | length == 0
            #   )
            # )
            # or
            # (
            #   rhelai_aws_key_name | length == 0 and
            #   rhelai_aws_key_material | default('') | length > 0
            # )

        - name: Set keyname
          ansible.builtin.set_fact:
            generated_aws_key: >-
              {{
                aws_key.key.name
                if
                  aws_key.key is defined and aws_key.key.name is defined
                else
                  rhelai_aws_key_name if rhelai_aws_key_name | default('') | length > 0
                else
                  rhelai_aws_key_default_name
              }}

        - name: Fix for AWS availability zone
          vars:
            # region: "{{ aws_region | default(lookup('ansible.builtin.env', 'AWS_REGION')) }}"
            ec2_networking_resources_vpc_name: "{{ rhelai_aws_resource_name }}-vpc"
            ec2_networking_resources_vpc_cidr_block: "{{ rhelai_aws_vpc_cidr }}"
            ec2_networking_resources_subnet_cidr_block: "{{ rhelai_aws_subnet_cidr }}"
          block:
            - name: Create VPC - fixed az
              amazon.aws.ec2_vpc_net:
                name: "{{ ec2_networking_resources_vpc_name }}"
                cidr_block: "{{ ec2_networking_resources_vpc_cidr_block }}"
              register: ec2_networking_resources_vpc_result

            - name: Create VPC subnet - fixed az
              amazon.aws.ec2_vpc_subnet:
                vpc_id: "{{ ec2_networking_resources_vpc_result.vpc.id }}"
                cidr: "{{ ec2_networking_resources_subnet_cidr_block }}"
                az: "{{ rhelai_aws_aws_region }}a"

        - name: Create RHEL AI VPC
          ansible.builtin.include_role:
            name: cloud.aws_ops.ec2_networking_resources
          vars:
            ec2_networking_resources_vpc_name: "{{ rhelai_aws_resource_name }}-vpc"
            ec2_networking_resources_vpc_cidr_block: "{{ rhelai_aws_vpc_cidr }}"
            ec2_networking_resources_subnet_cidr_block: "{{ rhelai_aws_subnet_cidr }}"
            ec2_networking_resources_sg_name: "{{ rhelai_aws_resource_name }}-sg"
            ec2_networking_resources_sg_description: RHEL AI Default SG
            ec2_networking_resources_sg_rules:
              - proto: tcp
                ports: 22
                cidr_ip: 0.0.0.0/0
              - proto: tcp
                ports: 8443
                cidr_ip: 0.0.0.0/0
              - proto: tcp
                ports: 8000
                cidr_ip: 0.0.0.0/0              
            ec2_networking_resources_create_igw: true
            aws_security_token: '{{ security_token | default(omit) }}'

        - name: Get instance info with provided name
          amazon.aws.ec2_instance_info:
            filters:
              "tag:Name": "{{ rhelai_aws_resource_name }}-instance"
              instance-state-name: ["pending", "running"]
          register: ec2_info_result

        - name: Create RHEL AI EC2 instance
          ansible.builtin.include_role:
            name: cloud.aws_ops.manage_ec2_instance
          vars:
            manage_ec2_instance_operation: create
            manage_ec2_instance_instance_name: "{{ rhelai_aws_resource_name }}-instance"
            manage_ec2_instance_instance_type: "{{ rhelai_aws_instance_type }}"
            manage_ec2_instance_ami_id: "{{ rhelai_aws_rhelai_ami }}"
            manage_ec2_instance_vpc_subnet_id: "{{ ec2_networking_resources_subnet_result.subnet.id }}"
            manage_ec2_instance_associate_security_groups: "{{ ec2_networking_resources_sg_result.group_id }}"
            manage_ec2_instance_associate_eip: false  # We'll associate EIP manually after creating it
            manage_ec2_instance_key_name: "{{ generated_aws_key }}"
            manage_ec2_instance_tags:
              Environment: RHEL-AI
              Component: LLM-Serving
            manage_ec2_instance_wait_for_state: true
            aws_security_token: '{{ security_token | default(omit) }}'
          when: ec2_info_result.instances is not defined or ec2_info_result.instances | length == 0
          register: ec2_instance_result

        - name: Get updated instance info
          amazon.aws.ec2_instance_info:
            filters:
              "tag:Name": "{{ rhelai_aws_resource_name }}-instance"
              instance-state-name: ["pending", "running"]
          register: ec2_info_updated

        - name: Create Elastic IP
          amazon.aws.ec2_eip:
            state: present
            tags:
              Name: "{{ rhelai_aws_resource_name }}-eip"
              Environment: RHEL-AI
          register: eip_result
          when: rhelai_aws_create_eip | default(false)

        - name: Associate Elastic IP with instance
          amazon.aws.ec2_eip:
            device_id: "{{ ec2_info_updated.instances[0].instance_id }}"
            public_ip: "{{ eip_result.public_ip }}"
            state: present
          when: 
            - rhelai_aws_create_eip | default(false)
            - eip_result.public_ip is defined
            - ec2_info_updated.instances | length > 0

        - name: Display instance and EIP information
          ansible.builtin.debug:
            msg:
              - "Instance ID: {{ ec2_info_updated.instances[0].instance_id }}"
              - "Instance Private IP: {{ ec2_info_updated.instances[0].private_ip_address }}"
              - "Elastic IP: {{ eip_result.public_ip | default('N/A') }}"
          when: ec2_info_updated.instances | length > 0
