---
- name: Simple EC2 Instance Provisioning with Elastic IP
  hosts: localhost
  gather_facts: false
  
  vars:
    # Basic instance configuration
    instance_name: "my-ec2-instance"
    instance_type: "t3.medium"
    ami_id: "ami-0c55b159cbfafe1f0"  # Update with your AMI ID
    aws_region: "us-east-1"
    key_name: "my-ssh-key"
    
    # Network configuration
    vpc_cidr: "10.0.0.0/16"
    subnet_cidr: "10.0.1.0/24"
    availability_zone: "us-east-1a"
    
    # Security group ports to open
    allowed_ports:
      - 22    # SSH
      - 80    # HTTP
      - 443   # HTTPS
      - 8443  # Custom HTTPS
    
    # Tags
    environment: "development"
    project: "demo"

  tasks:
    - name: Create VPC
      amazon.aws.ec2_vpc_net:
        name: "{{ instance_name }}-vpc"
        cidr_block: "{{ vpc_cidr }}"
        region: "{{ aws_region }}"
        tags:
          Name: "{{ instance_name }}-vpc"
          Environment: "{{ environment }}"
          Project: "{{ project }}"
      register: vpc

    - name: Create Internet Gateway
      amazon.aws.ec2_vpc_igw:
        vpc_id: "{{ vpc.vpc.id }}"
        region: "{{ aws_region }}"
        tags:
          Name: "{{ instance_name }}-igw"
      register: igw

    - name: Create Subnet
      amazon.aws.ec2_vpc_subnet:
        vpc_id: "{{ vpc.vpc.id }}"
        cidr: "{{ subnet_cidr }}"
        az: "{{ availability_zone }}"
        region: "{{ aws_region }}"
        map_public: true
        tags:
          Name: "{{ instance_name }}-subnet"
      register: subnet

    - name: Create Route Table
      amazon.aws.ec2_vpc_route_table:
        vpc_id: "{{ vpc.vpc.id }}"
        region: "{{ aws_region }}"
        subnets:
          - "{{ subnet.subnet.id }}"
        routes:
          - dest: "0.0.0.0/0"
            gateway_id: "{{ igw.gateway_id }}"
        tags:
          Name: "{{ instance_name }}-rt"
      register: route_table

    - name: Create Security Group
      amazon.aws.ec2_security_group:
        name: "{{ instance_name }}-sg"
        description: "Security group for {{ instance_name }}"
        vpc_id: "{{ vpc.vpc.id }}"
        region: "{{ aws_region }}"
        rules:
          - proto: tcp
            ports: "{{ allowed_ports }}"
            cidr_ip: "0.0.0.0/0"
            rule_desc: "Allow inbound traffic"
        tags:
          Name: "{{ instance_name }}-sg"
      register: security_group

    - name: Launch EC2 Instance
      amazon.aws.ec2_instance:
        name: "{{ instance_name }}"
        instance_type: "{{ instance_type }}"
        image_id: "{{ ami_id }}"
        key_name: "{{ key_name }}"
        vpc_subnet_id: "{{ subnet.subnet.id }}"
        security_group: "{{ security_group.group_id }}"
        network:
          assign_public_ip: true
        region: "{{ aws_region }}"
        wait: true
        state: running
        tags:
          Name: "{{ instance_name }}"
          Environment: "{{ environment }}"
          Project: "{{ project }}"
      register: ec2

    - name: Create Elastic IP
      amazon.aws.ec2_eip:
        region: "{{ aws_region }}"
        state: present
        tags:
          Name: "{{ instance_name }}-eip"
          Environment: "{{ environment }}"
      register: eip

    - name: Associate Elastic IP with Instance
      amazon.aws.ec2_eip:
        device_id: "{{ ec2.instance_ids[0] }}"
        public_ip: "{{ eip.public_ip }}"
        region: "{{ aws_region }}"
        state: present

    - name: Display Instance Information
      ansible.builtin.debug:
        msg:
          - "========================================="
          - "EC2 Instance Created Successfully"
          - "========================================="
          - "Instance ID: {{ ec2.instance_ids[0] }}"
          - "Instance Type: {{ instance_type }}"
          - "Private IP: {{ ec2.instances[0].private_ip_address }}"
          - "Elastic IP: {{ eip.public_ip }}"
          - "Region: {{ aws_region }}"
          - "Availability Zone: {{ availability_zone }}"
          - "VPC ID: {{ vpc.vpc.id }}"
          - "Subnet ID: {{ subnet.subnet.id }}"
          - "Security Group ID: {{ security_group.group_id }}"
          - "========================================="
          - "SSH Connection: ssh -i ~/.ssh/{{ key_name }}.pem ec2-user@{{ eip.public_ip }}"
          - "========================================="
